### ISSUE TITLE
您好，请问有laradock配置xdebug的相关教程吗？

### ISSUE THREAD

**Issue by sowhat233** [839891627/dnmp#1]
laradock配置xdebug 折腾了两天 网上的各种教程都不适用
所以来这里问问

**Comment by bolechen** [comment]
官方最近刚出了一个 laravel/sail ，可以了解一下

陈伯乐
2020年12月12日 +0800 20:15 sowhat233 <notifications@github.com>，写道：

**Comment by 839891627** [comment]
应该差不多。我配置了  xdebug 3

可以参考下我  config/php/php72.ini 是如何配置的。然后这个录了个视频
https://www.bilibili.com/video/BV1nV411b7T3?pop_share=1
