### ISSUE TITLE
关于容器内 A 项目 curl 访问 B 项目不同的解决方案

### ISSUE THREAD

**Issue by snakelis** [839891627/dnmp#2]
我目前是这样解决的，你可以参考下，希望对你有帮助
1. nginx 容器设置固定IP
    networks:
      lnmp:
        ipv4_address: 10.5.0.2
2. php 容器 添加 解析容器配置
    extra_hosts:
      - "test.local:10.5.0.2"

**Comment by 839891627** [comment]
嗯嗯。我也是这样解决的。 在 ##方案二中说明了。只是文档格式乱了 😂
